services:
  app:
    build: .
    working_dir: /app
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
      APP_ENV: development
      WAIT_FOR_DB_ON_START: "true"
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "gunicorn -b 0.0.0.0:5000 run:app"

  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: